name: Build and Push Docker Image

# This workflow runs every time you push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a standard Linux runner
    steps:
      # 1. Checks out a copy of your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Logs into the GitHub Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }} # Uses the secret we just created

      # 3. Builds your Docker image and pushes it to the registry
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner,, }}/fee-payment-portal:latest